//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.30 at 12:14:43 AM CST 
//


package com.hotels.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hotels.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hotels.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllHotelDetailsByNameRequest }
     * 
     */
    public GetAllHotelDetailsByNameRequest createGetAllHotelDetailsByNameRequest() {
        return new GetAllHotelDetailsByNameRequest();
    }

    /**
     * Create an instance of {@link GetAllAmenityDetailsByHotelResponse }
     * 
     */
    public GetAllAmenityDetailsByHotelResponse createGetAllAmenityDetailsByHotelResponse() {
        return new GetAllAmenityDetailsByHotelResponse();
    }

    /**
     * Create an instance of {@link AmenityDetails }
     * 
     */
    public AmenityDetails createAmenityDetails() {
        return new AmenityDetails();
    }

    /**
     * Create an instance of {@link GetAllHotelDetailsByNameResponse }
     * 
     */
    public GetAllHotelDetailsByNameResponse createGetAllHotelDetailsByNameResponse() {
        return new GetAllHotelDetailsByNameResponse();
    }

    /**
     * Create an instance of {@link HotelDetails }
     * 
     */
    public HotelDetails createHotelDetails() {
        return new HotelDetails();
    }

    /**
     * Create an instance of {@link SaveAmenityDetailsRequest }
     * 
     */
    public SaveAmenityDetailsRequest createSaveAmenityDetailsRequest() {
        return new SaveAmenityDetailsRequest();
    }

    /**
     * Create an instance of {@link SaveAmenityDetailsResponse }
     * 
     */
    public SaveAmenityDetailsResponse createSaveAmenityDetailsResponse() {
        return new SaveAmenityDetailsResponse();
    }

    /**
     * Create an instance of {@link SaveHotelDetailsRequest }
     * 
     */
    public SaveHotelDetailsRequest createSaveHotelDetailsRequest() {
        return new SaveHotelDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllHotelDetailsResponse }
     * 
     */
    public GetAllHotelDetailsResponse createGetAllHotelDetailsResponse() {
        return new GetAllHotelDetailsResponse();
    }

    /**
     * Create an instance of {@link SaveHotelDetailsResponse }
     * 
     */
    public SaveHotelDetailsResponse createSaveHotelDetailsResponse() {
        return new SaveHotelDetailsResponse();
    }

    /**
     * Create an instance of {@link AddAmenityDetailsToHotelDetailsRequest }
     * 
     */
    public AddAmenityDetailsToHotelDetailsRequest createAddAmenityDetailsToHotelDetailsRequest() {
        return new AddAmenityDetailsToHotelDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteHotelDetailsResponse }
     * 
     */
    public DeleteHotelDetailsResponse createDeleteHotelDetailsResponse() {
        return new DeleteHotelDetailsResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link DeleteAmenityDetailsResponse }
     * 
     */
    public DeleteAmenityDetailsResponse createDeleteAmenityDetailsResponse() {
        return new DeleteAmenityDetailsResponse();
    }

    /**
     * Create an instance of {@link RemoveAmenityDetailsToHotelDetailsResponse }
     * 
     */
    public RemoveAmenityDetailsToHotelDetailsResponse createRemoveAmenityDetailsToHotelDetailsResponse() {
        return new RemoveAmenityDetailsToHotelDetailsResponse();
    }

    /**
     * Create an instance of {@link DeleteHotelDetailsRequest }
     * 
     */
    public DeleteHotelDetailsRequest createDeleteHotelDetailsRequest() {
        return new DeleteHotelDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllAmenityDetailsResponse }
     * 
     */
    public GetAllAmenityDetailsResponse createGetAllAmenityDetailsResponse() {
        return new GetAllAmenityDetailsResponse();
    }

    /**
     * Create an instance of {@link AddAmenityDetailsToHotelDetailsResponse }
     * 
     */
    public AddAmenityDetailsToHotelDetailsResponse createAddAmenityDetailsToHotelDetailsResponse() {
        return new AddAmenityDetailsToHotelDetailsResponse();
    }

    /**
     * Create an instance of {@link DeleteAmenityDetailsRequest }
     * 
     */
    public DeleteAmenityDetailsRequest createDeleteAmenityDetailsRequest() {
        return new DeleteAmenityDetailsRequest();
    }

    /**
     * Create an instance of {@link GetHotelDetailsResponse }
     * 
     */
    public GetHotelDetailsResponse createGetHotelDetailsResponse() {
        return new GetHotelDetailsResponse();
    }

    /**
     * Create an instance of {@link RemoveAmenityDetailsToHotelDetailsRequest }
     * 
     */
    public RemoveAmenityDetailsToHotelDetailsRequest createRemoveAmenityDetailsToHotelDetailsRequest() {
        return new RemoveAmenityDetailsToHotelDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllHotelDetailsRequest }
     * 
     */
    public GetAllHotelDetailsRequest createGetAllHotelDetailsRequest() {
        return new GetAllHotelDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllAmenityDetailsByHotelRequest }
     * 
     */
    public GetAllAmenityDetailsByHotelRequest createGetAllAmenityDetailsByHotelRequest() {
        return new GetAllAmenityDetailsByHotelRequest();
    }

    /**
     * Create an instance of {@link GetAllAmenityDetailsRequest }
     * 
     */
    public GetAllAmenityDetailsRequest createGetAllAmenityDetailsRequest() {
        return new GetAllAmenityDetailsRequest();
    }

    /**
     * Create an instance of {@link GetHotelDetailsRequest }
     * 
     */
    public GetHotelDetailsRequest createGetHotelDetailsRequest() {
        return new GetHotelDetailsRequest();
    }

}
