//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.30 at 12:14:43 AM CST 
//


package com.hotels.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id_hotel" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="id_amenity" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idHotel",
    "idAmenity"
})
@XmlRootElement(name = "RemoveAmenityDetailsToHotelDetailsRequest")
public class RemoveAmenityDetailsToHotelDetailsRequest {

    @XmlElement(name = "id_hotel")
    protected long idHotel;
    @XmlElement(name = "id_amenity")
    protected long idAmenity;

    /**
     * Gets the value of the idHotel property.
     * 
     */
    public long getIdHotel() {
        return idHotel;
    }

    /**
     * Sets the value of the idHotel property.
     * 
     */
    public void setIdHotel(long value) {
        this.idHotel = value;
    }

    /**
     * Gets the value of the idAmenity property.
     * 
     */
    public long getIdAmenity() {
        return idAmenity;
    }

    /**
     * Sets the value of the idAmenity property.
     * 
     */
    public void setIdAmenity(long value) {
        this.idAmenity = value;
    }

}
