//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.27 at 12:38:44 PM CST 
//


package com.hotels.amenities;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hotels.amenities package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hotels.amenities
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllAmenityByHotelDetailsRequest }
     * 
     */
    public GetAllAmenityByHotelDetailsRequest createGetAllAmenityByHotelDetailsRequest() {
        return new GetAllAmenityByHotelDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteAmenityDetailsRequest }
     * 
     */
    public DeleteAmenityDetailsRequest createDeleteAmenityDetailsRequest() {
        return new DeleteAmenityDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllAmenityByHotelDetailsResponse }
     * 
     */
    public GetAllAmenityByHotelDetailsResponse createGetAllAmenityByHotelDetailsResponse() {
        return new GetAllAmenityByHotelDetailsResponse();
    }

    /**
     * Create an instance of {@link AmenityDetails }
     * 
     */
    public AmenityDetails createAmenityDetails() {
        return new AmenityDetails();
    }

    /**
     * Create an instance of {@link SaveAmenityDetailsRequest }
     * 
     */
    public SaveAmenityDetailsRequest createSaveAmenityDetailsRequest() {
        return new SaveAmenityDetailsRequest();
    }

    /**
     * Create an instance of {@link SaveAmenityDetailsResponse }
     * 
     */
    public SaveAmenityDetailsResponse createSaveAmenityDetailsResponse() {
        return new SaveAmenityDetailsResponse();
    }

    /**
     * Create an instance of {@link DeleteAmenityDetailsResponse }
     * 
     */
    public DeleteAmenityDetailsResponse createDeleteAmenityDetailsResponse() {
        return new DeleteAmenityDetailsResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

}
