//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.27 at 12:38:44 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://hotels.com/amenities", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hotels.amenities;
