//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.27 at 12:38:44 PM CST 
//


package com.hotels.amenities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AmenityDetails" type="{http://hotels.com/amenities}AmenityDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "amenityDetails"
})
@XmlRootElement(name = "SaveAmenityDetailsResponse")
public class SaveAmenityDetailsResponse {

    @XmlElement(name = "AmenityDetails", required = true)
    protected AmenityDetails amenityDetails;

    /**
     * Gets the value of the amenityDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AmenityDetails }
     *     
     */
    public AmenityDetails getAmenityDetails() {
        return amenityDetails;
    }

    /**
     * Sets the value of the amenityDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmenityDetails }
     *     
     */
    public void setAmenityDetails(AmenityDetails value) {
        this.amenityDetails = value;
    }

}
