//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.20 at 12:50:22 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.localhost.com/xml/hotels", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.localhost.xml.hotels;
